### PR TITLE
1.5.0

### LINKED ISSUE #129: autorestic as a Docker image
This looks promising for what I need. Would be good for it to be made available as a docker image with a `docker-compose.yml` with the appropriate volume mounts and configs.

Could this be made available please?

Thanks,

### PR DESCRIPTION
**Pull request by cupcakearmy**
- closes https://github.com/cupcakearmy/autorestic/issues/71
- closes https://github.com/cupcakearmy/autorestic/issues/84
- closes https://github.com/cupcakearmy/autorestic/issues/126
- closes #129

### CODE REVIEW

**Comment by haneef95** [comment]
Thanks, this is really helpful.

Could you list the persistent data locations/mount points please?

It'll help build the docker-compose file.

Thanks 😄

**Comment by cupcakearmy** [comment]
> Thanks, this is really helpful.
> 
> 
> 
> Could you list the persistent data locations/mount points please?
> 
> 
> 
> It'll help build the docker-compose file.
> 
> 
> 
> Thanks 😄 

What data do you mean exactly?
The docket image is an image with restic , auto restic and rclone

**Comment by haneef95** [comment]
When the docker image is deployed, it needs to be deployed with some volumes right?

Because, it'll be reading and storing various data right, like:
- Restic config
- Rclone config
- restic source data
- restic backup repo
- autorestic config
- etc...

Those are quite a few, it would be good to have a docker-compose example file with a list of all the volumes that it needs, and network ports that needs to be exposed, if any.

Thanks

**Comment by cupcakearmy** [comment]
The docker image is only providing the binaries.
How it is used is up to the user and I would argue out of the scope.

Maybe one could show a few examples.

**Comment by haneef95** [comment]
ofc, the admins should have the flexibility to choose that for themselves.

However, the it would be good to have some defaults stated, like with this officially supported 3rd party implementation:
https://github.com/Lobaro/restic-backup-docker#hooks
It states all the different options available to the admins, including hooks, variables, default volumes. etc...

And we could then use that to configure our environment.

Most application publishers have that included usually.

It would avoid having the fish for the info.

Thanks

**Comment by cupcakearmy** [comment]
Tracked in #139

**Pull request merged**
