### PR TITLE
add support for rest server backends

### PR DESCRIPTION
**Pull request by sumnerboy12**
Backend configuration would be;

```
rest_repo:
  type: rest
  path: http://backup:8001/repo_name
```

Would result in the following env var;
```
RESTIC_REPOSITORY=rest:http://backup:8001/repo_name
```

### CODE REVIEW

**Comment by cupcakearmy** [comment]
Ok awesome :) So I guess you have verified that this works? Unfortunately i don't have tests 😅

**Comment by sumnerboy12** [comment]
I have other scripts which run restic backups using `RESTIC_REPOSITORY=rest:http://blah` env vars to a local rest server. So I am pretty confident it will work ok. But I haven't tested this PR specifically.

**Comment by sumnerboy12** [comment]
Wasn't sure where I can update the docs relating to this change tho?

**Comment by cupcakearmy** [comment]
Ok, i think it should work too yes ;)
Thanks for the effort btw.
Docs are under autorestic/docs/md/backend/available.md
Then you need to build them again with `yarn run docs:build`

**Comment by sumnerboy12** [comment]
I have updated the docs now, so will leave to you to merge if you are happy. Sorry I don't know how to build the docs (I have been making these changes in the Github web IDE :) ).

**Comment by cupcakearmy** [comment]
Done :) Release is out

**Pull request merged**
